GET http://localhost:3000/users

###

GET http://localhost:3000/users/a1b2c3
Content-Type: application/json

###

POST  http://localhost:3000/users/
Content-Type: application/json

{
    "uid":"a1b2c3",
    "username":"Roger",
    "userLogin":"Roger",
}